// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guery.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	guery.proto

It has these top-level messages:
	Empty
	Location
	Heartbeat
	Instruction
	QuerySQL
	QueryResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Location struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Address      string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Port         int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	ChannelIndex int32  `protobuf:"varint,4,opt,name=channelIndex" json:"channelIndex,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Location) GetChannelIndex() int32 {
	if m != nil {
		return m.ChannelIndex
	}
	return 0
}

type Heartbeat struct {
	Location    *Location    `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Resource    int32        `protobuf:"varint,2,opt,name=resource" json:"resource,omitempty"`
	Instruction *Instruction `protobuf:"bytes,3,opt,name=instruction" json:"instruction,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Heartbeat) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Heartbeat) GetResource() int32 {
	if m != nil {
		return m.Resource
	}
	return 0
}

func (m *Heartbeat) GetInstruction() *Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

type Instruction struct {
	TaskId                int32  `protobuf:"varint,1,opt,name=taskId" json:"taskId,omitempty"`
	TaskType              int32  `protobuf:"varint,2,opt,name=taskType" json:"taskType,omitempty"`
	EncodedEPlanNodeBytes string `protobuf:"bytes,3,opt,name=encodedEPlanNodeBytes" json:"encodedEPlanNodeBytes,omitempty"`
}

func (m *Instruction) Reset()                    { *m = Instruction{} }
func (m *Instruction) String() string            { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()               {}
func (*Instruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Instruction) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Instruction) GetTaskType() int32 {
	if m != nil {
		return m.TaskType
	}
	return 0
}

func (m *Instruction) GetEncodedEPlanNodeBytes() string {
	if m != nil {
		return m.EncodedEPlanNodeBytes
	}
	return ""
}

type QuerySQL struct {
	SQL string `protobuf:"bytes,1,opt,name=SQL" json:"SQL,omitempty"`
}

func (m *QuerySQL) Reset()                    { *m = QuerySQL{} }
func (m *QuerySQL) String() string            { return proto.CompactTextString(m) }
func (*QuerySQL) ProtoMessage()               {}
func (*QuerySQL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QuerySQL) GetSQL() string {
	if m != nil {
		return m.SQL
	}
	return ""
}

type QueryResponse struct {
	ColumnNumber int32    `protobuf:"varint,1,opt,name=ColumnNumber" json:"ColumnNumber,omitempty"`
	ColumnName   []string `protobuf:"bytes,2,rep,name=ColumnName" json:"ColumnName,omitempty"`
	ColumnType   []string `protobuf:"bytes,3,rep,name=ColumnType" json:"ColumnType,omitempty"`
	ColumnValue  []string `protobuf:"bytes,4,rep,name=ColumnValue" json:"ColumnValue,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryResponse) GetColumnNumber() int32 {
	if m != nil {
		return m.ColumnNumber
	}
	return 0
}

func (m *QueryResponse) GetColumnName() []string {
	if m != nil {
		return m.ColumnName
	}
	return nil
}

func (m *QueryResponse) GetColumnType() []string {
	if m != nil {
		return m.ColumnType
	}
	return nil
}

func (m *QueryResponse) GetColumnValue() []string {
	if m != nil {
		return m.ColumnValue
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*Heartbeat)(nil), "pb.Heartbeat")
	proto.RegisterType((*Instruction)(nil), "pb.Instruction")
	proto.RegisterType((*QuerySQL)(nil), "pb.QuerySQL")
	proto.RegisterType((*QueryResponse)(nil), "pb.QueryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GueryMaster service

type GueryMasterClient interface {
	SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (GueryMaster_SendHeartbeatClient, error)
	Query(ctx context.Context, in *QuerySQL, opts ...grpc.CallOption) (*QueryResponse, error)
}

type gueryMasterClient struct {
	cc *grpc.ClientConn
}

func NewGueryMasterClient(cc *grpc.ClientConn) GueryMasterClient {
	return &gueryMasterClient{cc}
}

func (c *gueryMasterClient) SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (GueryMaster_SendHeartbeatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GueryMaster_serviceDesc.Streams[0], c.cc, "/pb.GueryMaster/SendHeartbeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &gueryMasterSendHeartbeatClient{stream}
	return x, nil
}

type GueryMaster_SendHeartbeatClient interface {
	Send(*Heartbeat) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type gueryMasterSendHeartbeatClient struct {
	grpc.ClientStream
}

func (x *gueryMasterSendHeartbeatClient) Send(m *Heartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gueryMasterSendHeartbeatClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gueryMasterClient) Query(ctx context.Context, in *QuerySQL, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/pb.GueryMaster/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GueryMaster service

type GueryMasterServer interface {
	SendHeartbeat(GueryMaster_SendHeartbeatServer) error
	Query(context.Context, *QuerySQL) (*QueryResponse, error)
}

func RegisterGueryMasterServer(s *grpc.Server, srv GueryMasterServer) {
	s.RegisterService(&_GueryMaster_serviceDesc, srv)
}

func _GueryMaster_SendHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GueryMasterServer).SendHeartbeat(&gueryMasterSendHeartbeatServer{stream})
}

type GueryMaster_SendHeartbeatServer interface {
	SendAndClose(*Empty) error
	Recv() (*Heartbeat, error)
	grpc.ServerStream
}

type gueryMasterSendHeartbeatServer struct {
	grpc.ServerStream
}

func (x *gueryMasterSendHeartbeatServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gueryMasterSendHeartbeatServer) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GueryMaster_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySQL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryMasterServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryMaster/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryMasterServer).Query(ctx, req.(*QuerySQL))
	}
	return interceptor(ctx, in, info, handler)
}

var _GueryMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GueryMaster",
	HandlerType: (*GueryMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _GueryMaster_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendHeartbeat",
			Handler:       _GueryMaster_SendHeartbeat_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "guery.proto",
}

// Client API for GueryExecutor service

type GueryExecutorClient interface {
	Quit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Duplicate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SendInstruction(ctx context.Context, in *Instruction, opts ...grpc.CallOption) (*Empty, error)
	GetOutputChannelLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error)
}

type gueryExecutorClient struct {
	cc *grpc.ClientConn
}

func NewGueryExecutorClient(cc *grpc.ClientConn) GueryExecutorClient {
	return &gueryExecutorClient{cc}
}

func (c *gueryExecutorClient) Quit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.GueryExecutor/Quit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gueryExecutorClient) Duplicate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.GueryExecutor/Duplicate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gueryExecutorClient) SendInstruction(ctx context.Context, in *Instruction, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.GueryExecutor/SendInstruction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gueryExecutorClient) GetOutputChannelLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := grpc.Invoke(ctx, "/pb.GueryExecutor/GetOutputChannelLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GueryExecutor service

type GueryExecutorServer interface {
	Quit(context.Context, *Empty) (*Empty, error)
	Duplicate(context.Context, *Empty) (*Empty, error)
	SendInstruction(context.Context, *Instruction) (*Empty, error)
	GetOutputChannelLocation(context.Context, *Location) (*Location, error)
}

func RegisterGueryExecutorServer(s *grpc.Server, srv GueryExecutorServer) {
	s.RegisterService(&_GueryExecutor_serviceDesc, srv)
}

func _GueryExecutor_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryExecutorServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryExecutor/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryExecutorServer).Quit(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GueryExecutor_Duplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryExecutorServer).Duplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryExecutor/Duplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryExecutorServer).Duplicate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GueryExecutor_SendInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instruction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryExecutorServer).SendInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryExecutor/SendInstruction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryExecutorServer).SendInstruction(ctx, req.(*Instruction))
	}
	return interceptor(ctx, in, info, handler)
}

func _GueryExecutor_GetOutputChannelLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryExecutorServer).GetOutputChannelLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryExecutor/GetOutputChannelLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryExecutorServer).GetOutputChannelLocation(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

var _GueryExecutor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GueryExecutor",
	HandlerType: (*GueryExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Quit",
			Handler:    _GueryExecutor_Quit_Handler,
		},
		{
			MethodName: "Duplicate",
			Handler:    _GueryExecutor_Duplicate_Handler,
		},
		{
			MethodName: "SendInstruction",
			Handler:    _GueryExecutor_SendInstruction_Handler,
		},
		{
			MethodName: "GetOutputChannelLocation",
			Handler:    _GueryExecutor_GetOutputChannelLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guery.proto",
}

func init() { proto.RegisterFile("guery.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0x6e, 0x9a, 0xe6, 0xae, 0x99, 0x5c, 0x39, 0x5d, 0x50, 0x42, 0x11, 0x29, 0xf1, 0x25, 0x08,
	0x56, 0xac, 0x3e, 0xf8, 0xec, 0x59, 0xce, 0x42, 0x3d, 0x6d, 0x2a, 0xbe, 0x6f, 0x92, 0xc1, 0x2b,
	0xa6, 0xbb, 0xcb, 0xfe, 0xc0, 0xf6, 0xdd, 0x7f, 0xc1, 0xbf, 0xc7, 0x7f, 0x4d, 0x76, 0x9b, 0xa4,
	0x89, 0xe8, 0xdb, 0x7c, 0xf3, 0x4d, 0x66, 0xbe, 0x6f, 0x67, 0x02, 0xd1, 0x37, 0x83, 0xf2, 0x38,
	0x17, 0x92, 0x6b, 0x4e, 0x86, 0x22, 0x4f, 0x2e, 0x21, 0x58, 0xee, 0x85, 0x3e, 0x26, 0x02, 0xc6,
	0x6b, 0x5e, 0x50, 0xbd, 0xe3, 0x8c, 0x10, 0x18, 0x31, 0xba, 0xc7, 0xd8, 0x9b, 0x79, 0x69, 0x98,
	0xb9, 0x98, 0xc4, 0x70, 0x49, 0xcb, 0x52, 0xa2, 0x52, 0xf1, 0xd0, 0xa5, 0x1b, 0x68, 0xab, 0x05,
	0x97, 0x3a, 0xf6, 0x67, 0x5e, 0x1a, 0x64, 0x2e, 0x26, 0x09, 0x5c, 0x15, 0xf7, 0x94, 0x31, 0xac,
	0x56, 0xac, 0xc4, 0x43, 0x3c, 0x72, 0x5c, 0x2f, 0x97, 0xfc, 0xf4, 0x20, 0xfc, 0x80, 0x54, 0xea,
	0x1c, 0xa9, 0x26, 0x29, 0x8c, 0xab, 0x7a, 0xbe, 0x9b, 0x1b, 0x2d, 0xae, 0xe6, 0x22, 0x9f, 0x37,
	0x9a, 0xb2, 0x96, 0x25, 0x53, 0x18, 0x4b, 0x54, 0xdc, 0xc8, 0x02, 0x9d, 0x94, 0x20, 0x6b, 0x31,
	0x79, 0x05, 0xd1, 0x8e, 0x29, 0x2d, 0x4d, 0xe1, 0x1a, 0xf9, 0xae, 0xd1, 0xb5, 0x6d, 0xb4, 0x3a,
	0xa7, 0xb3, 0x6e, 0x4d, 0xf2, 0x03, 0xa2, 0x0e, 0x47, 0x1e, 0xc3, 0x85, 0xa6, 0xea, 0xfb, 0xaa,
	0x74, 0x2a, 0x82, 0xac, 0x46, 0x76, 0xaa, 0x8d, 0xbe, 0x1c, 0x45, 0x3b, 0xb5, 0xc1, 0xe4, 0x0d,
	0x3c, 0x42, 0x56, 0xf0, 0x12, 0xcb, 0xe5, 0xe7, 0x8a, 0xb2, 0x3b, 0x5e, 0xe2, 0xbb, 0xa3, 0x46,
	0xe5, 0xe6, 0x87, 0xd9, 0xbf, 0xc9, 0xe4, 0x09, 0x8c, 0x37, 0x76, 0x1b, 0xdb, 0xcd, 0x9a, 0x3c,
	0x00, 0x7f, 0xbb, 0x59, 0xd7, 0x0f, 0x6e, 0xc3, 0xe4, 0x97, 0x07, 0x13, 0x47, 0x67, 0xa8, 0x04,
	0x67, 0x0a, 0xed, 0x9b, 0xde, 0xf0, 0xca, 0xec, 0xd9, 0x9d, 0xd9, 0xe7, 0x28, 0x6b, 0x7d, 0xbd,
	0x1c, 0x79, 0x0a, 0x50, 0x63, 0xbb, 0xbf, 0xe1, 0xcc, 0x4f, 0xc3, 0xac, 0x93, 0x39, 0xf3, 0xce,
	0x87, 0xdf, 0xe5, 0x9d, 0x93, 0x19, 0x44, 0x27, 0xf4, 0x95, 0x56, 0x06, 0xe3, 0x91, 0x2b, 0xe8,
	0xa6, 0x16, 0xf7, 0x10, 0xdd, 0x5a, 0x59, 0x1f, 0xa9, 0xd2, 0x28, 0xc9, 0x0b, 0x98, 0x6c, 0x91,
	0x95, 0xe7, 0x3d, 0x4e, 0xec, 0x63, 0xb7, 0x70, 0x1a, 0x5a, 0x78, 0xba, 0xb0, 0x41, 0xea, 0x91,
	0xe7, 0x10, 0x38, 0x53, 0xc4, 0x2d, 0xb7, 0xb1, 0x3f, 0x7d, 0xd8, 0xa2, 0xc6, 0x6d, 0x32, 0x58,
	0xfc, 0xf6, 0x60, 0xe2, 0x46, 0x2d, 0x0f, 0x58, 0x18, 0xcd, 0xad, 0xbb, 0xd1, 0xc6, 0xec, 0x34,
	0x39, 0x37, 0xed, 0xf5, 0x27, 0xcf, 0x20, 0x7c, 0x6f, 0x44, 0xb5, 0x2b, 0xa8, 0xc6, 0xff, 0x16,
	0xbd, 0x84, 0x6b, 0xab, 0xb8, 0xbb, 0xf3, 0xbf, 0x0f, 0xa4, 0xff, 0xc1, 0x5b, 0x88, 0x6f, 0x51,
	0x7f, 0x32, 0x5a, 0x18, 0x7d, 0x73, 0x3a, 0xe0, 0xf6, 0x4f, 0xe9, 0xdd, 0xe8, 0xb4, 0x87, 0x92,
	0x41, 0x7e, 0xe1, 0xfe, 0xb3, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xc1, 0xf8, 0xc8,
	0x76, 0x03, 0x00, 0x00,
}
