// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guery.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	guery.proto

It has these top-level messages:
	Empty
	Location
	Heartbeat
	Instruction
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Location struct {
	DataCenter string `protobuf:"bytes,1,opt,name=dataCenter" json:"dataCenter,omitempty"`
	Rack       string `protobuf:"bytes,2,opt,name=rack" json:"rack,omitempty"`
	Address    string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Name       string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *Location) GetRack() string {
	if m != nil {
		return m.Rack
	}
	return ""
}

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Heartbeat struct {
	Location    *Location    `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Resource    int32        `protobuf:"varint,2,opt,name=resource" json:"resource,omitempty"`
	Instruction *Instruction `protobuf:"bytes,3,opt,name=instruction" json:"instruction,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Heartbeat) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Heartbeat) GetResource() int32 {
	if m != nil {
		return m.Resource
	}
	return 0
}

func (m *Heartbeat) GetInstruction() *Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

type Instruction struct {
	TaskId               int32       `protobuf:"varint,1,opt,name=taskId" json:"taskId,omitempty"`
	TaskType             int32       `protobuf:"varint,2,opt,name=taskType" json:"taskType,omitempty"`
	InputLocations       []*Location `protobuf:"bytes,3,rep,name=inputLocations" json:"inputLocations,omitempty"`
	OutputLocations      []*Location `protobuf:"bytes,4,rep,name=outputLocations" json:"outputLocations,omitempty"`
	EncodedPlanNodeBytes string      `protobuf:"bytes,5,opt,name=encodedPlanNodeBytes" json:"encodedPlanNodeBytes,omitempty"`
}

func (m *Instruction) Reset()                    { *m = Instruction{} }
func (m *Instruction) String() string            { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()               {}
func (*Instruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Instruction) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Instruction) GetTaskType() int32 {
	if m != nil {
		return m.TaskType
	}
	return 0
}

func (m *Instruction) GetInputLocations() []*Location {
	if m != nil {
		return m.InputLocations
	}
	return nil
}

func (m *Instruction) GetOutputLocations() []*Location {
	if m != nil {
		return m.OutputLocations
	}
	return nil
}

func (m *Instruction) GetEncodedPlanNodeBytes() string {
	if m != nil {
		return m.EncodedPlanNodeBytes
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*Heartbeat)(nil), "pb.Heartbeat")
	proto.RegisterType((*Instruction)(nil), "pb.Instruction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GueryMaster service

type GueryMasterClient interface {
	SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (GueryMaster_SendHeartbeatClient, error)
}

type gueryMasterClient struct {
	cc *grpc.ClientConn
}

func NewGueryMasterClient(cc *grpc.ClientConn) GueryMasterClient {
	return &gueryMasterClient{cc}
}

func (c *gueryMasterClient) SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (GueryMaster_SendHeartbeatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GueryMaster_serviceDesc.Streams[0], c.cc, "/pb.GueryMaster/SendHeartbeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &gueryMasterSendHeartbeatClient{stream}
	return x, nil
}

type GueryMaster_SendHeartbeatClient interface {
	Send(*Heartbeat) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type gueryMasterSendHeartbeatClient struct {
	grpc.ClientStream
}

func (x *gueryMasterSendHeartbeatClient) Send(m *Heartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gueryMasterSendHeartbeatClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GueryMaster service

type GueryMasterServer interface {
	SendHeartbeat(GueryMaster_SendHeartbeatServer) error
}

func RegisterGueryMasterServer(s *grpc.Server, srv GueryMasterServer) {
	s.RegisterService(&_GueryMaster_serviceDesc, srv)
}

func _GueryMaster_SendHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GueryMasterServer).SendHeartbeat(&gueryMasterSendHeartbeatServer{stream})
}

type GueryMaster_SendHeartbeatServer interface {
	SendAndClose(*Empty) error
	Recv() (*Heartbeat, error)
	grpc.ServerStream
}

type gueryMasterSendHeartbeatServer struct {
	grpc.ServerStream
}

func (x *gueryMasterSendHeartbeatServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gueryMasterSendHeartbeatServer) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GueryMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GueryMaster",
	HandlerType: (*GueryMasterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendHeartbeat",
			Handler:       _GueryMaster_SendHeartbeat_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "guery.proto",
}

// Client API for GueryExecutor service

type GueryExecutorClient interface {
	Quit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Duplicate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SendInstruction(ctx context.Context, in *Instruction, opts ...grpc.CallOption) (*Empty, error)
}

type gueryExecutorClient struct {
	cc *grpc.ClientConn
}

func NewGueryExecutorClient(cc *grpc.ClientConn) GueryExecutorClient {
	return &gueryExecutorClient{cc}
}

func (c *gueryExecutorClient) Quit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.GueryExecutor/Quit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gueryExecutorClient) Duplicate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.GueryExecutor/Duplicate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gueryExecutorClient) SendInstruction(ctx context.Context, in *Instruction, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.GueryExecutor/SendInstruction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GueryExecutor service

type GueryExecutorServer interface {
	Quit(context.Context, *Empty) (*Empty, error)
	Duplicate(context.Context, *Empty) (*Empty, error)
	SendInstruction(context.Context, *Instruction) (*Empty, error)
}

func RegisterGueryExecutorServer(s *grpc.Server, srv GueryExecutorServer) {
	s.RegisterService(&_GueryExecutor_serviceDesc, srv)
}

func _GueryExecutor_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryExecutorServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryExecutor/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryExecutorServer).Quit(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GueryExecutor_Duplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryExecutorServer).Duplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryExecutor/Duplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryExecutorServer).Duplicate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GueryExecutor_SendInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instruction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GueryExecutorServer).SendInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GueryExecutor/SendInstruction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GueryExecutorServer).SendInstruction(ctx, req.(*Instruction))
	}
	return interceptor(ctx, in, info, handler)
}

var _GueryExecutor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GueryExecutor",
	HandlerType: (*GueryExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Quit",
			Handler:    _GueryExecutor_Quit_Handler,
		},
		{
			MethodName: "Duplicate",
			Handler:    _GueryExecutor_Duplicate_Handler,
		},
		{
			MethodName: "SendInstruction",
			Handler:    _GueryExecutor_SendInstruction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guery.proto",
}

func init() { proto.RegisterFile("guery.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0xad, 0x93, 0x38, 0x89, 0xc7, 0x4d, 0x23, 0xad, 0xaa, 0xca, 0xca, 0x21, 0xaa, 0xdc, 0x4b,
	0x2e, 0x4d, 0x55, 0xb7, 0xe2, 0xc4, 0x09, 0x88, 0x20, 0x12, 0x20, 0x30, 0xfc, 0xc0, 0xda, 0x3b,
	0x42, 0x56, 0x9c, 0x5d, 0x6b, 0xbd, 0x2b, 0xe1, 0x3b, 0x7c, 0x29, 0x3f, 0x82, 0x76, 0x13, 0x3b,
	0x4e, 0x08, 0xb7, 0x79, 0x33, 0xef, 0xcd, 0x9b, 0x9d, 0x59, 0xf0, 0x9f, 0x34, 0xca, 0x6a, 0x5e,
	0x48, 0xa1, 0x04, 0xe9, 0x14, 0x49, 0x38, 0x00, 0x77, 0xb1, 0x2e, 0x54, 0x15, 0xe6, 0x30, 0xbc,
	0x16, 0x29, 0x55, 0x99, 0xe0, 0x64, 0x0a, 0xc0, 0xa8, 0xa2, 0xe7, 0xc8, 0x15, 0xca, 0xc0, 0xf9,
	0xe9, 0xcc, 0xbc, 0xb8, 0x95, 0x21, 0x04, 0x7a, 0x92, 0xa6, 0xab, 0xa0, 0x63, 0x2b, 0x36, 0x26,
	0x01, 0x0c, 0x28, 0x63, 0x12, 0xcb, 0x32, 0xe8, 0xda, 0x74, 0x0d, 0x0d, 0x9b, 0xd3, 0x35, 0x06,
	0xee, 0x86, 0x6d, 0xe2, 0xf0, 0xc5, 0x01, 0xef, 0x0a, 0xa9, 0x54, 0x09, 0x52, 0x45, 0x66, 0x30,
	0xcc, 0xb7, 0xde, 0xd6, 0xcd, 0x8f, 0xbe, 0xce, 0x8b, 0x64, 0x5e, 0xcf, 0x13, 0x37, 0x55, 0x32,
	0x81, 0xa1, 0xc4, 0x52, 0x68, 0x99, 0xa2, 0x75, 0x77, 0xe3, 0x06, 0x93, 0xbf, 0xe0, 0x67, 0xbc,
	0x54, 0x52, 0xa7, 0xb6, 0x51, 0xd7, 0x36, 0x1a, 0x9b, 0x46, 0xcb, 0x5d, 0x3a, 0x6e, 0x73, 0xc2,
	0x37, 0x07, 0xfc, 0x56, 0x91, 0xfc, 0x80, 0xbe, 0xa2, 0xe5, 0x6a, 0xc9, 0xec, 0x18, 0x6e, 0xbc,
	0x45, 0xc6, 0xd6, 0x44, 0x8f, 0x55, 0xd1, 0xd8, 0xd6, 0x98, 0xfc, 0x87, 0x6f, 0x19, 0x2f, 0xb4,
	0xaa, 0xa7, 0x35, 0xef, 0xef, 0x7e, 0x78, 0xc2, 0x01, 0x87, 0x9c, 0xc0, 0x58, 0x68, 0xb5, 0x27,
	0xeb, 0x1d, 0x91, 0x1d, 0x92, 0x48, 0x04, 0xdf, 0x91, 0xa7, 0x82, 0x21, 0xbb, 0xcb, 0x29, 0xbf,
	0x15, 0x0c, 0xcf, 0x2a, 0x85, 0xe5, 0x76, 0xb9, 0x47, 0x6b, 0xd1, 0x29, 0xf8, 0x97, 0xe6, 0xec,
	0x37, 0xb4, 0x34, 0xd7, 0xfb, 0x0d, 0xa3, 0x07, 0xe4, 0x6c, 0xb7, 0xfe, 0x91, 0xb1, 0x6c, 0xe0,
	0xc4, 0x33, 0x70, 0xf3, 0x29, 0xbe, 0xcc, 0x9c, 0xe8, 0xd5, 0x81, 0x91, 0x95, 0x2f, 0x9e, 0x31,
	0xd5, 0x4a, 0x48, 0x32, 0x85, 0xde, 0xbd, 0xce, 0x14, 0xd9, 0x11, 0xf7, 0x34, 0xe4, 0x17, 0x78,
	0x17, 0xba, 0xc8, 0xb3, 0x94, 0x2a, 0xfc, 0x94, 0xf4, 0x07, 0xc6, 0x66, 0x8a, 0xf6, 0xf6, 0x0f,
	0x6f, 0xb5, 0x27, 0x48, 0xfa, 0xf6, 0xd3, 0xfe, 0x7b, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xd9,
	0xbf, 0x5b, 0xc3, 0x02, 0x00, 0x00,
}
